### ISSUE TITLE
Start and end time in sound event features

### ISSUE THREAD

**Issue by vogelbam** [mbsantiago/soundevent#6]
Hi,

The function `geometry.features._compute_bounding_box_features` returns `duration`, `low_freq`, `high_freq` and `bandwidth`. Is there any reason why start and end time of the bounding box have not been included? I believe these are useful temporal features as well and it's quite tedious to extract them manually each time.

**Comment by mbsantiago** [comment]
Hi @vogelbam!

My thought was that `start_time` and `end_time` are not intrinsic features of a sound event, as they are relative to some point in time (which might change). I was envisaging that these "features" could be used to compare some acoustic features of sound events, and in this context I thought that comparing their start time or end time didn't make much sense. If you want to get the start time and end time, I would recommend you use the `soundevent.geometry.compute_bounds` function, this will return `start_time`, `low_freq`, `end_time`, `high_freq` respectively.

Hope this helps and happy to discuss this further. 

Santiago

**Comment by vogelbam** [comment]
Hi Santiago,

you're right, the relative location of a sound event in an audio snippet does not help much with identifying its event type.

Thanks for the clarification,
Markus
